apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
  labels:
    app: rag-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        image: simple_rag-pipeline-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "rag-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "ragdb"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "Password"
        - name: OLLAMA_BASE_URL
          value: "http://host.minikube.internal:11434"
        - name: LLM_MODEL
          value: "llama3.2"
        - name: EMBED_MODEL
          value: "nomic-embed-text"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: rag-backend
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: rag-backend
